# Generated by Django 5.0.4 on 2024-05-01 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Universitate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('fakultet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.fakultet')),
            ],
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('universitet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.universitate')),
            ],
        ),
        migrations.AddField(
            model_name='fakultet',
            name='universitet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.universitate'),
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fakultet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.fakultet')),
                ('fan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.fan')),
                ('guruh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.guruh')),
                ('universitet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.universitate')),
                ('ustoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.ustoz')),
            ],
        ),
    ]
